version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_URL=postgresql://projectuser:1234@db:5432/restrictedcpfs
      - TYPEORM_MIGRATIONS=src/database/migrations/*.ts
      - TYPEORM_MIGRATIONS_DIR=src/database/migrations
      - POSTGRES_SSL_MODE=disable
    networks:
      - restricted-cpfs-network
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=projectuser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=restrictedcpfs
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - restricted-cpfs-network
networks:
  restricted-cpfs-network:
volumes:
  pg-data:
