version: "3"
services:
  app:
    image: leobazan/restrictedcpfs:1.0
    ports:
      - "8080:8080"
    environment:
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_URL=postgresql://projectuser:1234@db:5432/restrictedcpfs
    networks:
      - restricted-cpfs-network
    command: ./docker-entrypoint.sh
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=projectuser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=restrictedcpfs
      - POSTGRES_SSL_MODE=disable
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - restricted-cpfs-network
networks:
  restricted-cpfs-network:
volumes:
  pg-data:
